### ISSUE TITLE
Can this method be used for missing data in time series？

### ISSUE THREAD

**Issue by baidu2018** [iiradia/kPOD#1]
Hello, I have some electricity time series data, in which there are missing values in the electricity data to be predicted. Can I use the kpod method to fill in the missing values?

**Comment by iiradia** [comment]
Hi @baidu2018, thanks for checking out kPOD. Although the kPOD method internally fills the missing data at each iteration, the purpose of the algorithm is only for clustering so you wouldn't be able to fill in the missing values themselves using kPOD. 

Hope this helps!

**Comment by baidu2018** [comment]
Thank you very much for your reply! Thank you for your kpod method!
